name = "gleamdb"
version = "1.7.1"
description = "A high-performance, analytical Datalog engine for Gleam"
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = ">= 0.34.0"
gleam_erlang = ">= 0.25.0"
gleam_otp = ">= 0.10.0"

[dev-dependencies]
gleeunit = ">= 1.0.0"
